version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
  pgadmin:
    image: dpage/pgadmin4:6.16
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  # backend:
  #   build: .
  #   command: uvicorn main:app --reload
  #   volumes:
  #     - .:/code/
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
