version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4:6.16
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  frontend:
    # stdin_open: true # put you inside the container
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      # - "app/node_modules" # in case you need to debug some node_modules
      - "./frontend/:/app" # HOT Reload enabled
    depends_on:
      - db
  backend:
    build: ./backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --host 0.0.0.0'
    volumes:
      - ./backend/app:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
